### ISSUE TITLE
Voting rules on budget module

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#1]
## Context : 
We added a voting method where user have to select a total of N (configurable in admin) projects to be able to cast their vote ([code is here](https://github.com/OpenSourcePolitics/decidim/tree/master/decidim-budgets)). The default voting method "Vote Threshold" (where the selected projects must amount a min percentage of the total budget) and the voting method cannot be activated at the same time. 

## Simple description of the feature: 
- we'd like to impose a minimum number of project selected per category.
- that minimum amount can be selected per category
- min amount of selected project per category rule can be used for both voting methods : threshold and total number of project to select.

## Link to mockups : 
[https://www.figma.com/file/fpFI5pko3p2MEq8Ud51Yy9/Voting-rules-for-budget?node-id=1%3A33](https://www.figma.com/file/fpFI5pko3p2MEq8Ud51Yy9/Voting-rules-for-budget?node-id=1%3A33)

Here are detailed mockups of how this should work.

### Admin configuration page
- [ ]  Add seperate voting rules section
- [ ]  Add checkbox for min per category rule
- [ ]  Add number input field for each category
- [ ]  List of category should be flatten to account for sub-categories
Sum of minimums for all categories cannot me over total number of projects.
![admin-edit](https://user-images.githubusercontent.com/11473995/61704897-1351fe00-ad45-11e9-8c65-afa2d1f21a2e.png)

### Project index - No selection made by user
- [ ] Add voting rules section (text is generated depending on the voting rules in admin)
![index-no-selection](https://user-images.githubusercontent.com/11473995/61704906-1816b200-ad45-11e9-9a24-7e307e0800a9.png)

### Project index - existing selection
- [ ] Add "Your selection title"
- [ ] Bellow selection show number of projects left to select
![index with selection](https://user-images.githubusercontent.com/11473995/61704980-37154400-ad45-11e9-85f8-432af40a2302.png)

**Comment by paarals** [comment]
Hi @virgile-dev, You don't have a mockup about the user experience selecting projects. We made this proposal:

![imatge](https://user-images.githubusercontent.com/40388743/62204649-f42f1e00-b38d-11e9-8d78-b7cebd65714f.png)

Do you want to include it or leave it as it is now?

**Comment by virgile-dev** [comment]
@paarals I was thinking we should leave it out for now so we don't introduce unknown complexity with a UI that I'm not sure will work in the long term. 

In my mockups the idea is to set out the voting rules, and to show in the user's selection how many projects are left in total and are required for each category.

Is the rest clear enough for you guys ?

**Comment by paarals** [comment]
Ok @virgile-dev, perfect! Just one more question: 
In the case of the selection rules. We understand that we select the percentage option or the minimum project option. That is, if you select "Number of projectes selected", "minimum projects to select per category" is also displayed as an optional field. Right?

**Comment by virgile-dev** [comment]
@paarals you cannot select at the same time : 
- minimum budget percentage rule
- number of project selected

**You do have to choose one of the rules above**.

Additionnaly you can add the "minimum projects to select per category" rule but it's not obligatory. I hope this makes things clearer.

**Comment by paarals** [comment]
thanks @virgile-dev. And minimum projects to select x category rule works with the two options or just with number or project selected?
