### ISSUE TITLE
Registration form improvement with 2 steps + 1 onboarding screen

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#11]
## Tech related
- Approved proposal in Meta Decidim : https://meta.decidim.org/processes/roadmap/f/122/proposals/14855
- Hence this can be coded directly on a PR to master
- Deadline 10/12/2019

## Context
We’d like to improve the registration process for new users. The actual process is quite long and difficult, and we think Decidim should be more accessible and appealing.

## Proposed solution

Then, we propose that the registration form should be fragmented in two steps :
- The first one asking the user his email and password + tos acceptation (better GDPR wise)
- The second one his name, nickname and newsletter agreement

Furthermore, in order to encourage users to fill their profiles and improve the social network aspect of Decidim, we would like to add at the end of this process an interstitial screen.

It would offer the user the possibility to :
- Download his avatar picture
- Add his personal website and Bio
- Fill his interests
The user can skip this step or save those parameters.

**Callback :** Then, the user is redirected to the page he wanted to go (to create a proposal, the page of a proposal, create an initiative, etc.)

## Mockups
![Inscription Metadecidim](https://user-images.githubusercontent.com/11473995/69742332-e5d6f000-113c-11ea-9fcd-506a8bfe5d8b.png)

**Comment by amiedes** [comment]
I'm gonna take care of this also 😄
