### ISSUE TITLE
Add versioning capabilities to initiatives

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#18]
## User story
**Is your feature request related to a problem? Please describe.** 
Currently an admin can apply all the changes it wants to an initiative. There is no way to track these changes. It's not transparent. 

**Describe the solution you'd like** 
We should have a versioning system for petitions like we have for proposals and results. The Decidim versioning system on proposals and results offer the following features : 
- List of versions
- Version author
- Date of version
- Different ways of comparing addition and deletions : unified/side by side
- Changes are highlighted : text deleted is highlighted in red and text added is highlighted in green. (an example [here](https://meta.decidim.org/processes/decidim-gov/f/961/collaborative_drafts/9/versions/2))

Changes that should be tracked : 
- Text changes to title, description
- State changes
- Changes in authorship (if we have time) 

**Describe alternatives you've considered** 
None 

**Additional context**  
![mockup](https://meta-decidim-production.s3.amazonaws.com/uploads/decidim/attachment/file/2571/big_Capture_d_écran_2020-03-23_à_20.36.59.png)

**Does this issue could impact on users private data?** 
No

## Acceptance criteria
- [ ] As a visitor on a initiative page I have a link to check the different versions of the initiative
- [ ] As a visitor when clicking on a version I can see what has changed thanks to the versioning visualization layout

**Comment by paulinebessoles** [comment]
**-> [Metadecidim proposal](https://meta.decidim.org/processes/roadmap/f/122/proposals/15130)**

**Comment by ace** [comment]
Decidim uses a gem (paper_trail) and common concerns/code for versioning different models. Adding that funcionality to initiatives shouldn't be a big amount of work.
Only exception is tracking commitee members. That would probably involve a more complex development since it's not part of the initiative model but an association.

**Comment by virgile-dev** [comment]
Hey @ace great news !
Let's leave out of the scope the tracking of co-authors for now.

**Comment by ace** [comment]
https://github.com/decidim/decidim/pull/5935
