### ISSUE TITLE
Create "matrix" question type for the survey module

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#2]
## Context
There is a need for more complex question type like "question matrix" feature by [Kobotools](https://kobo.humanitarianresponse.info).

![Capture d’écran 2019-08-05 à 16 51 28](https://user-images.githubusercontent.com/11473995/62473604-5e3a2f80-b7a1-11e9-9cea-e244206fb452.png)

## Feature outline
- [ ] As an admin I want to enable grid like questions where I can create rows and columns and choose the labels
- [ ] As an admin I want  to be able to choose an answer type per row (unsure) / question 
Simple choice --> Have to tick one column
Mutliple choices --> Can tick several column
Short answer --> Can input short text in colum

I would discard sorting and long answer as they don't seem fit to implement in a grid

**Comment by microstudi** [comment]
First approach analysed:

1. A new type of question is created: "matrix question". When selected, appears to the admin a similar behavior as the "simple question" or "multiple question" with 2 types of subgroups: rows (question) and columns (answers) with a free multilanguage text to configure.
2. A new select would configure the type of matrix: single (select one option per row), multiple (select multiple columns per row) or free-text (answer anything in any row).
3. When mandatory validation will force to fulfill all the fields, if not mandatory the user would be able to send the form half-filled.

**Comment by microstudi** [comment]
In a second analysis, I think the type of matrix should be single or multiple only. And then add the free-text option when defining a column with a checkbox "allow free text in this column". This would help to define a column with the case "another..."

**Comment by paulinebessoles** [comment]
![Matrix question(1)](https://user-images.githubusercontent.com/52420208/73253830-8a1cf780-41bd-11ea-955d-4f76fb541d9c.png)

@microstudi were you thinking about this ?

**Comment by virgile-dev** [comment]
@paulinebessoles (dope mockup) @microstudi This looks perfect to me.

**Comment by microstudi** [comment]
Great!, but I am not sure about the drag&drop feature. Maybe there are to many lines/boxes, maybe the title "COLUMNS" and "ROWS" can be headers without padding. And, instead the word "Question" in columns maybe "answer" or just "text"

**Comment by paulinebessoles** [comment]
Hi Ivan, thanks for the feedback ! 

Indeed, the drag&drop feature is not essential for rows and columns. 
For the ROWS & COLUMNS Title, if you find it easier it's all good. 
Finally, your right about the Question word, my mistake 😁

It's all good for @virgile-dev and I !
