### ISSUE TITLE
Allow the author of an initiative to choose the end of signature collection period

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#22]
**Is your feature related to a problem?**
The law doesn't always describe a fixed period for signature collection. It is problematic for the institution to decide for the citizen when they could actually choose it freely.

**Describe the solution you'd like**
As an admin, I want to be able to enable/disable the possibility for users to choose their own end of signature collection period when creating their initiative. = config option on the initiative type

As an author of an initiative, I want to be able to select an end of signature collection period when editing the step 4 of my initiative creation form.

After the initiative has been published, the author can't change the end of signature collection period.
After the initiative has been published, the admin can change the end of signature collection period.

**Additional context**
Meta Decidim proposal : https://meta.decidim.org/processes/roadmap/f/122/proposals/15128

**Does this issue could impact on users private data ?**
No

**Acceptance criteria**

- [  ] Config checkbox in admin initiative type configuration form to enable / disable the feature
- [  ] Display date selector for end date signature collection period in the initiative creation wizard in step 4
- [  ] Display date selector for end date signature collection period in the admin (initiative edit form) panel for the common user and allow him to edit the date until it is sent to technical validation

**Mockups**
[User choose the end of signature collection period.pdf](https://github.com/OpenSourcePolitics/dev/files/4479711/User.choose.the.end.of.signature.collection.period.pdf)

**Comment by ace** [comment]
https://github.com/decidim/decidim/pull/5998

**Comment by ace** [comment]
Just to be sure, when is the author unable to change the date anymore? Solution text above says after published, but acceptance criteria says when sent to technical validation.
