### ISSUE TITLE
Export all initiatives as and admin (part I)

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/dev#23]
**User story**
As an admin, I want tobe able to export all initiatives in a structured format (json and csv) 

**Is your feature related to a problem?**
Initiatives cannot be exported right now, it's a problem for collaboration and follow through with non admins of the platform. Often admins keep an external csv file where they keep track of initiatives adding extra information.

**Describe the solution you'd like**

How the admin can request the export 
- [ ] Add a button "Export" on the `/admin/initiatives` page, on click a drop down opens with the download format available
![Group 84](https://user-images.githubusercontent.com/11473995/80092399-05930880-8563-11ea-87d9-e87e0ae893b8.png)

- [ ] When clicking on the button, a success message displays saying the export is being prepared and will be sent by email.
<img width="1221" alt="Capture d’écran 2020-04-23 à 13 03 18" src="https://user-images.githubusercontent.com/11473995/80092296-d8465a80-8562-11ea-90ad-296a8f7c8a7e.png">
- [ ] The admin receives a notification email with a zip file containing the export file

The export file contains the following data at least (the more columns the best actually): 
- [ ] Title
- [ ] Description
- [ ] Type
- [ ] Scope
- [ ] Signature type 
- [ ] State
- [ ] Creation date
- [ ] Publication date
- [ ] End of signature collection date
- [ ] Authors names (should include promoting committee members)
- [ ] Authors ID (should include promoting committee members)
- [ ] Number of signatures
- [ ] Description

**Additional context**
Meta Decidim proposal https://meta.decidim.org/processes/roadmap/f/122/proposals/15123

**Comment by ace** [comment]
https://github.com/decidim/decidim/pull/6070
