### ISSUE TITLE
Allow the administrator to disable the addition of attachments on an initiative type

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#24]
**User story**
As administrator, I want to be able to disable attachments on an initiative type, so that authors and co-authors of a petition cannot add attachments to their petition (in the creation wizard and in the admin).

**Is your feature related to a problem?**
Attachements are cumbersome to moderate and can be infected with viruses. 

**Describe the solution you'd like**
It should be an admin choice (configuration option) to enable or disable attachement on an initiative type.

- [ ] Add a configuration flag for the initiative type allowing to enable/disable the ability to add attachments to a petition of that petition type. 
Text for checkbox : "Enable attachements"
Default value : unchecked

- [ ] When disabled the menu in the admin doesn't display
<img width="1234" alt="Capture d’écran 2020-04-23 à 12 26 14" src="https://user-images.githubusercontent.com/11473995/80089058-ae3e6980-855d-11ea-89bb-e9f001eafd20.png">

- [ ] When disabled the button to add a joint file in the initiative wizard doesn't display ( [check this PR](https://github.com/decidim/decidim/pull/5844) )
![image](https://user-images.githubusercontent.com/11473995/80088992-8f3fd780-855d-11ea-96c0-0017f7914b0f.png)

**Additional context**
Meta Decidim proposal : https://meta.decidim.org/processes/roadmap/f/122/proposals/15127
We've done a PR on impacting how user can attach a file, please take into account while making your own PR : https://github.com/decidim/decidim/pull/5844

**Does this issue could impact on users private data ?**
No

**Comment by ace** [comment]
Should admins be allowed to add attachments even if it is configured to not allow them?

**Comment by virgile-dev** [comment]
@ace what is the default behaviour that you have right now ?
I'd personnal go with none are allowed to add attachement but would like the opinion of @valentinchaput and @paulinebessoles

**Comment by ace** [comment]
I had no default for admins.
I was restricting attachments through permissions. If flag is not set, user has no permissions on attachments, that's the simplest way to filter everything out. 
But, admins can not be restricted that way, they have default permissions on the admin module that can't be changed (without changing the admin module).
So, depending on the decision, I'll have to change that approach.
I have 'mixed feelings' on this. I tend to agree with you, none allowed. But then, that is a change regarding other things we've allowed/restricted, like the custom signature end date, so not fully sure.

**Comment by virgile-dev** [comment]
ok thanks for the feedback @ace 
I discussed it with @paulinebessoles  let's go with the simpler approach then. Admin can add joint files even if it is configured to not allow them.

**Comment by virgile-dev** [comment]
Hey @ace 
Can you link the PR please ?

**Comment by ace** [comment]
Sure!
https://github.com/decidim/decidim/pull/6036
