### ISSUE TITLE
Adapt module "No signature allowed module" to decidim/decidim#5998

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#26]
**Context**
In https://github.com/OpenSourcePolitics/dev/issues/22 we allowed the user to choose the end date for the signature collection period. ([link to PR not merged yet](https://github.com/decidim/decidim/pull/5998)

We need to make this feature compatible to this external module that we built for a specific need of our client : https://github.com/OpenSourcePolitics/decidim-module-initiatives_nosignature_allowed/issues

Basically this module allows the user to choose no to collect any signature. The initiative stills as default beginning and end of collection signature dates associated. Don't worry about this.

It makes no sense to display a field "End of signature collection period" when the no signature checkbox is ticked.

**What needs to be done**
Make a PR to our  module https://github.com/OpenSourcePolitics/decidim-module-initiatives_nosignature_allowed/issues so that 
- [ ] When the user checks the flag "No signature" the field "End of signature collection period" is hidden in the step 4 of this initiative creation wizard.

**Comment by ace** [comment]
https://github.com/OpenSourcePolitics/decidim-module-initiatives_nosignature_allowed/pull/5
