### ISSUE TITLE
Harmonize initiative filters FO

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#29]
**Is your feature request related to a problem?**
Recently front-office filters for proposals where revamped. It now allows mutlti-select thanks to checkboxes. It allows for more discoverability as you can make more precise selections that the radio button offers.

Checkout proposal filters
<img width="971" alt="Capture d’écran 2020-05-06 à 12 42 43" src="https://user-images.githubusercontent.com/11473995/81168379-2e6dc180-8f97-11ea-8291-c92f32f0ccd8.png">
https://sensei.osp.cat/processes/tempore-ab/f/12/?locale=en

**Describe the solution you'd like**
I'd like to revamp the filter box in that logic. I'll take this opportunity to add couple changes so that the filtering is improved 

- [ ] add subfilters to closed so that people can filter by status "accepted" "rejected"
- [ ] add a filter for initiatives that received an answer

**Does this issue could impact on users private data? Ex. issues related with user's sign up/sign in process, verifications, invitations, sensitive data like email, IP addresses, etc.**
No 

**Additionnel context**
Mockup
<img width="495" alt="Capture d’écran 2020-05-06 à 12 49 19" src="https://user-images.githubusercontent.com/11473995/81168860-15b1db80-8f98-11ea-8924-39d95ea0b2cb.png">
[Metadecidim proposal](https://meta.decidim.org/processes/roadmap/f/122/proposals/15234)

**Comment by ace** [comment]
Shouldn't we change the scopes selector, so it integrates in the new design as in proposals? It feels strange to keep it on its own.

**Comment by paulinebessoles** [comment]
You're completely right! Thank you for the question. 
It's better if the scope selector integrates the new design.

**Comment by ace** [comment]
https://github.com/decidim/decidim/pull/6090
