### ISSUE TITLE
Initiative searchbar enhancement (FO & BO)

### ISSUE THREAD

**Issue by paulinebessoles** [OpenSourcePolitics/dev#30]
### User story
As a user, I want to be able to search initiatives by initiative ID number and user name, nickname in the initiatives FO index searchbar. 
As an admin, I want to be able to search initiatives by initiative ID number, user name and nickname in the initiatives BO & FO index searchbar. 

### Is your feature related to a problem?
Right now, users and admins can only search initiatives by description or title. When I'm searching for an initiative, I'd like to be able to search for a specific initiative of a specific person.

### Describe the solution you'd like

**FO** 
- [x] Allow the user to search by initiative ID number, user name and user nickname
![image](https://user-images.githubusercontent.com/52420208/80979316-77066d00-8e27-11ea-83d6-9a1e86b635d9.png)

**BO**
- [x] Allow the admin to search by initiative ID number, user name and user nickname
- [x] Change the searchbar text for : "Search by title, description, ID or author name"

![image](https://user-images.githubusercontent.com/52420208/80979398-93a2a500-8e27-11ea-84bc-d6743b5bbc2e.png)

### Additional context
-> [Metadecidim proposal](https://meta.decidim.org/processes/roadmap/f/122/proposals/15121)

**Comment by ace** [comment]
https://github.com/decidim/decidim/pull/6086
