### ISSUE TITLE
Add areas to initiatives

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#32]
## **Is your feature request related to a problem? Please describe.**

Initiatives cannot be associated to an area like other participatory spaces.
You can check where areas are configurable : https://osp-decidim.dev.aspgems.com/admin/areas

## **Describe the solution you'd like**
As a user I want to be able to associate an area to initiatives during my initiative creation and when editing my initiative in the back office.

As a user I want to be able to filter initiatives in the index by area using a dropdown menu.

### Back-Office
- [x] Enable areas on initiatives

- [x] Allow admin and users to add an area to an initiative

    - [x] Add a dropdown field on the /edit form of initiatives that displays all the areas.
    - [x]  The area can be changed by the admin at any moment from the moment the initiative have been sent to technical validation, but can never be set to empty.

<img width="961" alt="Capture d’écran 2020-05-08 à 13 05 59" src="https://user-images.githubusercontent.com/11473995/81400173-cfda4c00-912c-11ea-91d3-a7dbaa0edd79.png">

- [x] Add a config flag to the initiative type that allows admin to enable and disable the possibility for authors to add an area to their initiatives
<img width="726" alt="Capture d’écran 2020-05-08 à 13 01 57" src="https://user-images.githubusercontent.com/11473995/81400236-ef717480-912c-11ea-876a-15dbad5eec68.png">

- [x] When the initiative is updated, the area will be displayed automatically on initiative card & show in FO (see below)

- [x] Add a filter for areas on the list of `admin/initiatives`
<img width="951" alt="Capture d’écran 2020-05-12 à 12 25 36" src="https://user-images.githubusercontent.com/11473995/81673562-248f0700-944c-11ea-8392-0c7ff72b4f1e.png">

### Front-Office

- [x] Show area on initiative card

- [x] Show area on initiative page
<img width="911" alt="Capture d’écran 2020-05-12 à 12 20 23" src="https://user-images.githubusercontent.com/11473995/81673512-10e3a080-944c-11ea-8267-ca2473389473.png">

- [ ] Add a filtering block to initiative index
<img width="938" alt="Capture d’écran 2020-05-08 à 12 57 40" src="https://user-images.githubusercontent.com/11473995/81399682-b71d6680-912b-11ea-9145-617e88aed1b6.png">

- [ ] When clicking on the area the user is redirected to a filtered index with iniatives associated to that area (same as scopes and type

## **Describe alternatives you've considered**

None

## **Does this issue could impact on users private data?**

No

**Comment by ace** [comment]
I'm not sure I fully understand this requirement
_The area can be changed by the admin at any moment from the moment the initiative have been sent to technical validation, but can never be set to empty._

Does that mean that the area will be required for all initiatives and can't be empty at all or that once an initiative is assigned an area it can't be emptied, but initiatives without area can remain like that?

**Comment by ace** [comment]
And a doubt. Will it be possible to add the area on initiative creation? The issue seems to talk just about the edit action. If so, in the fill_data step of the creation?

**Comment by paulinebessoles** [comment]
> I'm not sure I fully understand this requirement
> _The area can be changed by the admin at any moment from the moment the initiative have been sent to technical validation, but can never be set to empty._
> 
> Does that mean that the area will be required for all initiatives and can't be empty at all or that once an initiative is assigned an area it can't be emptied, but initiatives without area can remain like that?

Thanks for the questions @ace, the second one is the good one : once an initiative is assigned an area it can't be emptied, but initiatives without area can remain like that. The area can still be changed but not emptied.

**Comment by ace** [comment]
Thanks for the answers @paulinebessoles.

I had removed my second question upon re-reading the description of the issue and finding the proposed solution is referencing initiatives creation (I was looking for a check item about that). 

Now, your answer makes that paragraph wrong (it states a user can add an area on both creation and edition), should we remove that text from the description to avoid the confusion?

**Comment by paulinebessoles** [comment]
I'm sorry for the confusion, I didn't knew about the updates of the spec. Forget about what I said, the description is the good one. I'll modify my comment :)

**Comment by ace** [comment]
Ok, thanks!

**Comment by ace** [comment]
> once an initiative is assigned an area it can't be emptied, but initiatives without area can remain like that. The area can still be changed but not emptied.

Just to be sure, is that for everyone or just for admins, once the initiative has gone into validation? In other words, can the author clear the area while editing the initiative, before sending to technical validation?

**Comment by ace** [comment]
One design detail to have some debate. Areas can be arranged in area_types. The select for area shows that using grouped values, like this

![Captura de pantalla 2020-05-15 a las 13 42 44](https://user-images.githubusercontent.com/3958/82046847-00ccfa80-96b2-11ea-8ce0-e8675c66da54.png)

For the BO filter, it's impossible to get such effect. We could try some kind of nesting approach (show a first level filter with the types and then the areas) but that would require some (non trivial) changes in the admin module and probably some discussion about it with the core team.

So, we can just show the area name (could be a problem if two areas from different area types share the same name), or we can add the area type name in front of the area name, like this

![Captura de pantalla 2020-05-15 a las 13 41 04](https://user-images.githubusercontent.com/3958/82047049-67521880-96b2-11ea-85a5-94ba7f1f38bf.png)

Opinions?

We'll have a similar problem in the FO filter too.

**Comment by virgile-dev** [comment]
Hey @ace 
> Just to be sure, is that for everyone or just for admins, once the initiative has gone into validation? In other words, can the author clear the area while editing the initiative, before sending to technical validation?

A user / admin should always be able to empty the field by choosing the empty default value in a dropdown.

**Comment by virgile-dev** [comment]
@ace 
> So, we can just show the area name (could be a problem if two areas from different area types share the same name)

I'd go with the first and most simple option. Just display the name.

**Comment by virgile-dev** [comment]
@ace can you link your PR here please :)

**Comment by ace** [comment]
Sure, as soon as I create it :) Finishing the specs now.

**Comment by ace** [comment]
PR https://github.com/decidim/decidim/pull/6111

Pending the FO search/filter changes, waiting for the redesign PR review/approval/merge to add it to the new box. I'm keeping this issue on the To do column for that.

**Comment by virgile-dev** [comment]
@ace Nice ! Can you add it to your deploy that would be perfect so I can test it ?

**Comment by ace** [comment]
@virgile-dev I'm working on that. As I expected, a lot of conflicts when merging this branch with all the previous work. At least it will serve as training for those same conflicts in the PRs.

**Comment by virgile-dev** [comment]
OK ! I'll test locally for now.

**Comment by ace** [comment]
Deployed! I'm fixing some rubocop issues on the PR, but that doesn't affect the deploy, so you can test there. I've checked the area enabled flag in the 'Pariatur...' type and then set an area to two of its initiatives. The filter is a bit... unusable with all the areas in that instance :(
Have fun with the tests ;)
