### ISSUE TITLE
[Custom AN] Only admin can select an area for the initiative

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#34]
This is a custom piece of code for client **AN**.
As a base branch you are to use this one : https://github.com/aspgems/decidim/tree/feature/add_areas_to_initiatives (or the decidim develop if it's already merged)

One the new branch we are going to add the following specificity : 
When areas are activated on the initiative type only the admin should be able to select them using the drop down list from the back-office. 

- [ ] In the initiative creation wizard the dropdown list to select the area should be hidden
<img width="475" alt="Capture d’écran 2020-05-20 à 17 16 35" src="https://user-images.githubusercontent.com/11473995/82464302-36ad1d00-9abe-11ea-94aa-0d7d9112ce38.png">
- [ ] As a user (no admin privileges)  in the back-office the area dropdown list shouldn't appear in the initiation edit form
<img width="969" alt="Capture d’écran 2020-05-20 à 17 18 34" src="https://user-images.githubusercontent.com/11473995/82464295-33b22c80-9abe-11ea-9a7c-c0d1cdc7a09c.png">

**Comment by ace** [comment]
This is done, but I'm not sure what to do with it. Pushing the branch to the repo for now.

**Comment by virgile-dev** [comment]
Can you link the code the branch or the PR @ace ?

**Comment by ace** [comment]
Of course! https://github.com/aspgems/decidim/tree/custom_an/admin_only_areas
I'm prefixing this issues with `custom_an`, so they are easy to find.
