### ISSUE TITLE
[Initiatives] Allow "anonymous" (no Decidim account) Signatures / Votes with Omniauth fingerprint

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/dev#6]
**Feature description**
As a user I want to be able to sign (vote) an initiative :  
- without being logged in with a Decidim account
- with an identity validation from an external service (Omniauth)

The validation should be done with the existing Omniauth login callback, without the creation of a Decidim user account and using the UID defined by the Omniauth strategies.

Even if we say "Anonymous", the personal data form options should be available for this signature option.

**Context**
This use case comes from a client who wish : 
- maximum proof of anonymity for the signature (the less info we store on the platform, the better)
- identity validation to guarantee that a same person cannot vote twice

The external identity service we plan to use ([FranceConnect](https://franceconnect.gouv.fr) / OpenID) will provide identity validation in our context.

### Initiative form : 
- Add a new signature type "Omniauth"
- Add the list of the available Omniauth strategies

### Initiative page : 
- Display the Omniauth button on the vote form.

## Signature Workflow :  
1. Visit the initiative page
2. Click on the "Sign / Vote" buttton
3. Popup with an help text + Omniauth button
4. _Omniauth login request / callback phase_
5. Back to the end on the initiative vote workflow (personnal data form, success alert ...)

**Comment by oriolgual** [comment]
This has been a popular request in the past, and it has some technical implications. From the user point of view, I guess we can make it work as if they don't have a user account, although they'd have it. Not using a user account for this would involve a really big rewrite and I highly encourage not doing it. 

What I'd do is extend the current managed users feature, so not only admins can use it, but also end users who could login in using only a verification method. Admins would probably have to enable this on a per-participatory space basis.

Does this seem right?

**Comment by virgile-dev** [comment]
@oriolgual we are afraid it might not correspond to the expected client user flow.
I'm not discarding your solution as I trust you on the "big rewrite" thing. 
Using managed users is an interesting solution, my main concerns are about anonymity so let's dig a little more. 

Your idea is to fill the managed user profile with anon data like a random string ?
What would be the user flow exactly ?
- Click on sign
- omniauth process
- callback to site
- sign
- end of session after 30 min (or shorter, could be parametrable ?)

Let's brainstorm !

**Comment by oriolgual** [comment]
I think we could do it with the same workflow you proposed initially, and adding the end of session after 30 minutes (although this is optional).
